export type User = {
  id: number;
  username: string;
  full_name: string;
  phone: string;
  email: string;
  is_admin: number;
  is_blocked?: number;
};

export type Option = {
  id: number;
  question_id: number;
  text: string;
};

export type QuestionType = 'multiple_choice' | 'checkbox' | 'text' | 'paragraph';

export type Question = {
  id: number;
  survey_id: number;
  text: string;
  image_url?: string;
  type?: QuestionType;
  options: Option[];
  correct_option_id?: number;
};

export type SurveyType = 'internal' | 'google' | 'test';

export type Survey = {
  id: number;
  title: string;
  description: string;
  creator_id: number;
  creator_name: string;
  created_at: string;
  total_participants: number;
  questions: Question[];
  rating?: number;
  is_private?: number;
  access_code?: string;
  image_url?: string;
  is_active?: number;
  expires_at?: string;
  google_form_url?: string;
  google_view_url?: string;
  google_edit_url?: string;
  is_google_linked?: number;
  survey_type?: SurveyType;
};

export type VoteResult = {
  question_id: number;
  question_text: string;
  options: {
    id: number;
    text: string;
    count: number;
  }[];
};

export type Language = 'uz' | 'ru' | 'en';

export const translations = {
  uz: {
    welcome: "Xush kelibsiz",
    login: "Kirish",
    register: "Ro'yxatdan o'tish",
    username: "Foydalanuvchi nomi",
    password: "Parol",
    fullName: "To'liq ism",
    phone: "Telefon",
    email: "Email",
    surveys: "So'rovnomalar",
    createSurvey: "Yangi so'rovnoma",
    title: "Sarlavha",
    description: "Tavsif",
    options: "Variantlar",
    addOption: "Variant qo'shish",
    vote: "Ovoz berish",
    results: "Natijalar",
    profile: "Profil",
    statistics: "Statistika",
    settings: "Sozlamalar",
    language: "Til",
    theme: "Mavzu",
    light: "Yorug'",
    dark: "Qorong'i",
    logout: "Chiqish",
    save: "Saqlash",
    totalVotes: "Umumiy ovozlar",
    noSurveys: "Hozircha so'rovnomalar yo'q",
    createFirst: "Birinchi so'rovnomangizni yarating",
    alreadyVoted: "Siz allaqachon ovoz bergansiz",
    edit: "Tahrirlash",
    delete: "O'chirish",
    questions: "Savollar",
    addQuestion: "Savol qo'shish",
    creating: "Yaratilmoqda...",
    editing: "Tahrirlanmoqda...",
    totalSurveys: "So'rovnomalar",
    activity: "Faollik",
    popularSurveys: "Mashhur so'rovnomalar",
    question: "Savol",
    votes: "ovoz",
    of: "dan",
    confirmDelete: "O'chirishni tasdiqlaysizmi?",
    cancel: "Bekor qilish",
    error: "Xatolik yuz berdi",
    sendCode: "Kod yuborish",
    verifyCode: "Tasdiqlash kodi",
    codeSent: "Tasdiqlash kodi emailingizga yuborildi",
    resendCode: "Kodni qayta yuborish",
    deleteAccount: "Hisobni o'chirish",
    confirmDeleteAccount: "Hisobingizni o'chirishni tasdiqlaysizmi? Barcha ma'lumotlaringiz o'chib ketadi.",
    manageUsers: "Foydalanuvchilarni boshqarish",
    block: "Bloklash",
    unblock: "Blokdan chiqarish",
    userDeleted: "Foydalanuvchi o'chirildi",
    userBlocked: "Foydalanuvchi bloklandi",
    userUnblocked: "Foydalanuvchi blokdan chiqarildi",
    confirmDeleteUser: "Foydalanuvchini o'chirishni tasdiqlaysizmi? Uning barcha ovozlari ham o'chiriladi.",
    atLeastOneQuestion: "Kamida bitta savol bo'lishi shart",
    manageSurveys: "So'rovnomalarni boshqarish",
    stop: "To'xtatish",
    activate: "Faollashtirish",
    surveyStopped: "So'rovnoma to'xtatildi",
    surveyActivated: "So'rovnoma faollashtirildi",
    expiresAt: "Tugash vaqti",
    expired: "Muddati tugagan",
    timeLeft: "Qolgan vaqt",
    optional: "ixtiyoriy",
    support: "Qo'llab-quvvatlash",
    message: "Xabar",
    send: "Yuborish",
    messageSent: "Xabaringiz yuborildi. Tez orada javob beramiz.",
    supportDescription: "Savollaringiz yoki takliflaringiz bo'lsa, bizga yozing.",
    back: "Orqaga",
    rating: "Baholash",
    isPrivate: "Maxfiy so'rovnoma",
    accessCode: "Kirish kodi",
    enterCode: "Kodni kiriting",
    invalidCode: "Noto'g'ri kod",
    public: "Ochiq",
    private: "Maxfiy",
    fiveDigitCode: "5 xonali kod",
    googleFormIntegration: "Google Forms integratsiyasi",
    googleFormUrl: "Google Form URL (Action URL)",
    googleViewUrl: "Google Form Ko'rish Linki",
    pushToGoogleForm: "Google Formga yuborish",
    googleFormLinked: "Google Formga bog'langan",
    pushSuccess: "So'rovnoma muvaffaqiyatli Google Formga ulandi!",
    internalSurveys: "Oddiy so'rovnomalar",
    googleSurveys: "Google Forms so'rovnomalari",
    testSurveys: "Testlar",
    surveyType: "So'rovnoma turi",
    questionType: "Savol turi",
    multipleChoice: "Bir nechta tanlov",
    checkbox: "Belgilash katakchasi",
    shortAnswer: "Qisqa javob",
    paragraph: "Paragraf",
    correctAnswer: "To'g'ri javob",
    score: "Natija",
    testCompleted: "Test yakunlandi",
    yourScore: "Sizning natijangiz",
    outOf: "dan",
    correct: "To'g'ri",
    incorrect: "Noto'g'ri",
    googleEditUrl: "Google Form Tahrirlash Linki",
    viewGoogleForm: "Google Formni ko'rish",
    editGoogleForm: "Google Formni tahrirlash",
    scriptInstructions: "Google Form yaratish uchun quyidagi skriptni nusxalang va Google Apps Script-da ishlating. Skript avtomatik ravishda barcha savollarni yaratadi va kerakli linklarni qaytaradi."
  },
  ru: {
    welcome: "Добро пожаловать",
    login: "Вход",
    register: "Регистрация",
    username: "Имя пользователя",
    password: "Пароль",
    fullName: "Полное имя",
    phone: "Телефон",
    email: "Email",
    surveys: "Опросы",
    createSurvey: "Новый опрос",
    title: "Заголовок",
    description: "Описание",
    options: "Варианты",
    addOption: "Добавить вариант",
    vote: "Голосовать",
    results: "Результаты",
    profile: "Профиль",
    statistics: "Статистика",
    settings: "Настройки",
    language: "Язык",
    theme: "Тема",
    light: "Светлая",
    dark: "Темная",
    logout: "Выйти",
    save: "Сохранить",
    totalVotes: "Всего голосов",
    noSurveys: "Опросов пока нет",
    createFirst: "Создайте свой первый опрос",
    alreadyVoted: "Вы уже проголосовали",
    edit: "Редактировать",
    delete: "Удалить",
    questions: "Вопросы",
    addQuestion: "Добавить вопрос",
    creating: "Создание...",
    editing: "Редактирование...",
    totalSurveys: "Опросы",
    activity: "Активность",
    popularSurveys: "Популярные опросы",
    question: "Вопрос",
    votes: "голосов",
    of: "из",
    confirmDelete: "Подтвердите удаление?",
    cancel: "Отмена",
    error: "Произошла ошибка",
    sendCode: "Отправить код",
    verifyCode: "Код подтверждения",
    codeSent: "Код подтверждения отправлен на вашу почту",
    resendCode: "Переотправить код",
    deleteAccount: "Удалить аккаунт",
    confirmDeleteAccount: "Вы уверены, что хотите удалить свой аккаунт? Все ваши данные будут удалены.",
    manageUsers: "Управление пользователями",
    block: "Блокировать",
    unblock: "Разблокировать",
    userDeleted: "Пользователь удален",
    userBlocked: "Пользователь заблокирован",
    userUnblocked: "Пользователь разблокирован",
    confirmDeleteUser: "Вы уверены, что хотите удалить пользователя? Все его голоса также будут удалены.",
    atLeastOneQuestion: "Необходим хотя бы один вопрос",
    manageSurveys: "Управление опросами",
    stop: "Остановить",
    activate: "Активировать",
    surveyStopped: "Опрос остановлен",
    surveyActivated: "Опрос активирован",
    expiresAt: "Дата окончания",
    expired: "Срок истек",
    timeLeft: "Осталось времени",
    optional: "необязательно",
    support: "Поддержка",
    message: "Сообщение",
    send: "Отправить",
    messageSent: "Ваше сообщение отправлено. Мы скоро ответим.",
    supportDescription: "Если у вас есть вопросы или предложения, напишите нам.",
    back: "Назад",
    rating: "Оценка",
    isPrivate: "Закрытый опрос",
    accessCode: "Код доступа",
    enterCode: "Введите код",
    invalidCode: "Неверный код",
    public: "Открытый",
    private: "Закрытый",
    fiveDigitCode: "5-значный код",
    googleFormIntegration: "Интеграция с Google Forms",
    googleFormUrl: "URL Google Формы (Action URL)",
    googleViewUrl: "Ссылка для просмотра Google Формы",
    pushToGoogleForm: "Отправить в Google Форму",
    googleFormLinked: "Связано с Google Формой",
    pushSuccess: "Опрос успешно привязан к Google Форме!",
    internalSurveys: "Обычные опросы",
    googleSurveys: "Опросы Google Forms",
    testSurveys: "Тесты",
    surveyType: "Тип опроса",
    questionType: "Тип вопроса",
    multipleChoice: "Множественный выбор",
    checkbox: "Флажки",
    shortAnswer: "Краткий ответ",
    paragraph: "Абзац",
    correctAnswer: "Правильный ответ",
    score: "Результат",
    testCompleted: "Тест завершен",
    yourScore: "Ваш результат",
    outOf: "из",
    correct: "Правильно",
    incorrect: "Неправильно",
    googleEditUrl: "Ссылка для редактирования Google Формы",
    viewGoogleForm: "Посмотреть Google Форму",
    editGoogleForm: "Редактировать Google Форму",
    scriptInstructions: "Скопируйте следующий скрипт и используйте его в Google Apps Script для создания Google Формы. Скрипт автоматически создаст все вопросы и вернет необходимые ссылки."
  },
  en: {
    welcome: "Welcome",
    login: "Login",
    register: "Register",
    username: "Username",
    password: "Password",
    fullName: "Full Name",
    phone: "Phone",
    email: "Email",
    surveys: "Surveys",
    createSurvey: "New Survey",
    title: "Title",
    description: "Description",
    options: "Options",
    addOption: "Add Option",
    vote: "Vote",
    results: "Results",
    profile: "Profile",
    statistics: "Statistics",
    settings: "Settings",
    language: "Language",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    logout: "Logout",
    save: "Save",
    totalVotes: "Total Votes",
    noSurveys: "No surveys yet",
    createFirst: "Create your first survey",
    alreadyVoted: "You have already voted",
    edit: "Edit",
    delete: "Delete",
    questions: "Questions",
    addQuestion: "Add Question",
    creating: "Creating...",
    editing: "Editing...",
    totalSurveys: "Surveys",
    activity: "Activity",
    popularSurveys: "Popular Surveys",
    question: "Question",
    votes: "votes",
    of: "of",
    confirmDelete: "Confirm delete?",
    cancel: "Cancel",
    error: "An error occurred",
    sendCode: "Send Code",
    verifyCode: "Verification Code",
    codeSent: "Verification code sent to your email",
    resendCode: "Resend Code",
    deleteAccount: "Delete Account",
    confirmDeleteAccount: "Are you sure you want to delete your account? All your data will be removed.",
    manageUsers: "Manage Users",
    block: "Block",
    unblock: "Unblock",
    userDeleted: "User deleted",
    userBlocked: "User blocked",
    userUnblocked: "User unblocked",
    confirmDeleteUser: "Are you sure you want to delete the user? All their votes will also be deleted.",
    atLeastOneQuestion: "At least one question is required",
    manageSurveys: "Manage Surveys",
    stop: "Stop",
    activate: "Activate",
    surveyStopped: "Survey stopped",
    surveyActivated: "Survey activated",
    expiresAt: "Expiration date",
    expired: "Expired",
    timeLeft: "Time left",
    optional: "optional",
    support: "Support",
    message: "Message",
    send: "Send",
    messageSent: "Your message has been sent. We will respond soon.",
    supportDescription: "If you have any questions or suggestions, please write to us.",
    back: "Back",
    rating: "Rating",
    isPrivate: "Private Survey",
    accessCode: "Access Code",
    enterCode: "Enter Code",
    invalidCode: "Invalid Code",
    public: "Public",
    private: "Private",
    fiveDigitCode: "5-digit code",
    googleFormIntegration: "Google Forms Integration",
    googleFormUrl: "Google Form URL (Action URL)",
    googleViewUrl: "Google Form View Link",
    pushToGoogleForm: "Push to Google Form",
    googleFormLinked: "Linked to Google Form",
    pushSuccess: "Survey successfully linked to Google Form!",
    internalSurveys: "Internal Surveys",
    googleSurveys: "Google Forms Surveys",
    testSurveys: "Tests",
    surveyType: "Survey Type",
    questionType: "Question Type",
    multipleChoice: "Multiple Choice",
    checkbox: "Checkbox",
    shortAnswer: "Short Answer",
    paragraph: "Paragraph",
    correctAnswer: "Correct Answer",
    score: "Score",
    testCompleted: "Test Completed",
    yourScore: "Your Score",
    outOf: "out of",
    correct: "Correct",
    incorrect: "Incorrect",
    googleEditUrl: "Google Form Edit Link",
    viewGoogleForm: "View Google Form",
    editGoogleForm: "Edit Google Form",
    scriptInstructions: "Copy the following script and use it in Google Apps Script to create a Google Form. The script will automatically create all questions and return the necessary links."
  },
};
